### ISSUE TITLE
master fails to build

### ISSUE THREAD

**Issue by mintar** [jotaraul/upgmpp#3]
Hi Raul,

I just noticed that the current master doesn't build, at least not on Ubuntu 14.04. This is the error I'm getting:

    [ 23%] Built target base
    Linking CXX shared library ../libUPGMplusplus-inference.so
    CMakeFiles/inference.dir/decoding.o: In function `decodeExactRec(UPGMpp::CGraph&, std::map<unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<unsigned long, std::allocator<unsigned long> > > > > const&, unsigned long, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, double&, bool)':
    decoding.cpp:(.text+0x1290): multiple definition of `decodeExactRec(UPGMpp::CGraph&, std::map<unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<unsigned long, std::allocator<unsigned long> > > > > const&, unsigned long, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, double&, bool)'
    CMakeFiles/inference.dir/inference_MAP.o:inference_MAP.cpp:(.text+0x13d7): first defined here
    CMakeFiles/inference.dir/decoding.o: In function `updateResults(std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, std::map<unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<unsigned long, std::allocator<unsigned long> > > > >&)':
    decoding.cpp:(.text+0x6d68): multiple definition of `updateResults(std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, std::map<unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<unsigned long, std::allocator<unsigned long> > > > >&)'
    CMakeFiles/inference.dir/inference_MAP.o:inference_MAP.cpp:(.text+0x7135): first defined here
    collect2: error: ld returned 1 exit status
    make[2]: *** [libs/libUPGMplusplus-inference.so] Error 1
    make[1]: *** [libs/inference/CMakeFiles/inference.dir/all] Error 2
    make: *** [all] Error 2
    
This bug was introduced in 934dbf2; the commit before builds just fine.

**Comment by jotaraul** [comment]
Hi Martin!

Thanks for the advice! Now it should work. I just renamed the
inference.cpp/hpp and decoding.cpp/hpp to more appropriated names:
inference_marginals and inference_MAP respectively. For some reason the old
files were still on git. The names of the inference methods have also
changed, but it is easy to check the new ones. The ICM decoding method is
now called CICMInferenceMAP, Let me know if you have any problem!

How are you? And your projects? Some weeks ago I finished the tests
employing your 15 scenes dataset and different CRF configurations, you can
find a summary of this in: (our paper path)/Tests/Results Raul/summary.txt.
Take a look to it when you have time :)

See you máquina.

2015-05-26 15:10 GMT+02:00 Martin Günther <notifications@github.com>:

> Hi Raul,
>
> I just noticed that the current master doesn't build, at least not on
> Ubuntu 14.04. This is the error I'm getting:
>
> [ 23%] Built target base
> Linking CXX shared library ../libUPGMplusplus-inference.so
> CMakeFiles/inference.dir/decoding.o: In function `decodeExactRec(UPGMpp::CGraph&, std::map<unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<unsigned long, std::allocator<unsigned long> > > > > const&, unsigned long, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, double&, bool)':
> decoding.cpp:(.text+0x1290): multiple definition of `decodeExactRec(UPGMpp::CGraph&, std::map<unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<unsigned long, std::allocator<unsigned long> > > > > const&, unsigned long, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, double&, bool)'
> CMakeFiles/inference.dir/inference_MAP.o:inference_MAP.cpp:(.text+0x13d7): first defined here
> CMakeFiles/inference.dir/decoding.o: In function `updateResults(std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, std::map<unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<unsigned long, std::allocator<unsigned long> > > > >&)':
> decoding.cpp:(.text+0x6d68): multiple definition of `updateResults(std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, std::map<unsigned long, std::vector<unsigned long, std::allocator<unsigned long> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::vector<unsigned long, std::allocator<unsigned long> > > > >&)'
> CMakeFiles/inference.dir/inference_MAP.o:inference_MAP.cpp:(.text+0x7135): first defined here
> collect2: error: ld returned 1 exit status
> make[2]: *** [libs/libUPGMplusplus-inference.so] Error 1
> make[1]: *** [libs/inference/CMakeFiles/inference.dir/all] Error 2
> make: *** [all] Error 2
>
> This bug was introduced in 934dbf2
> <https://github.com/jotaraul/upgmpp/commit/934dbf28bbe208af936879bc99ce4d5213e19e31>;
> the commit before builds just fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jotaraul/upgmpp/issues/3>.
>



-- 
Raúl

**Comment by mintar** [comment]
It compiles now, thanks!
